CREATE DATABASE IF NOT EXISTS SQLTEST;
USE SQLTEST;
DROP TABLE IF EXISTS TBL_VOTES;
CREATE TABLE  IF NOT EXISTS TBL_VOTES ( name CHAR(10), TBL_VOTES INT );
INSERT INTO TBL_VOTES VALUES ('Smith',10), ('Jones',15), ('White',20), ('Black',40), ('Green',50), ('Brown',20);
SELECT NAME, TBL_VOTES FROM TBL_VOTES ORDER BY TBL_VOTES DESC;