DELIMITER $$
CREATE DATABASE IF NOT EXISTS SQLTEST;
USE SQLTEST;
DROP PROCEDURE IF EXISTS SP_DELIMIT_AND_DISPLAY;
CREATE PROCEDURE SP_DELIMIT_AND_DISPLAY()
begin
DECLARE NAME_VAR VARCHAR(50); 
DECLARE ID_VAR INT; 
DECLARE COUNTER INT;
DECLARE WORD VARCHAR(50);
DECLARE done INT DEFAULT FALSE;
DECLARE CUR CURSOR FOR SELECT * FROM DELIMT_TEST;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

DROP TABLE IF EXISTS TEMP_DELIMT_TEST;
CREATE TABLE TEMP_DELIMT_TEST( ID INT, NAME VARCHAR(50) );

OPEN CUR;

DELIMIT_LOOP:LOOP
	FETCH CUR INTO ID_VAR,NAME_VAR;	
	IF done THEN
      LEAVE DELIMIT_LOOP;
	 END IF; 
SET COUNTER=length(NAME_VAR);
		WHILE COUNTER >0
	DO
		SET WORD=SUBSTRING_INDEX(NAME_VAR,'|',1);		
		SET NAME_VAR = trim(substring(NAME_VAR,length(WORD)+2));
		INSERT INTO TEMP_DELIMT_TEST VALUES (ID_VAR,WORD);
		SET COUNTER=length(NAME_VAR);			
	END WHILE;
  END LOOP DELIMIT_LOOP;	   
CLOSE CUR;
SELECT * FROM TEMP_DELIMT_TEST;
DROP TABLE IF EXISTS TEMP_DELIMT_TEST;
END$$
DELIMITER ;
